export const GET_CONTACT_DETAIL_REQUEST = "GET_CONTACT_DETAIL_REQUEST";
export const SAVE_CONTACT_DETAILS = "SAVE_CONTACT_DETAILS";
export const SEND_CONTACT_DETAILS = "SEND_CONTACT_DETAILS";
export const UPDATE_CONTACT_DETAILS="UPDATE_CONTACT_DETAILS";
export const REMOVE_CONTACT_DETAILS="REMOVE_CONTACT_DETAILS";